### ISSUE TITLE
Serving Limit Exceeded

### ISSUE THREAD

**Issue by PatSpiegel** [madcoda/php-youtube-api#42]
exception 'Exception' with message 'Error 403 Serving Limit Exceeded : servingLimitExceeded' in /var/www/vendor/madcoda/php-youtube-api/src/Madcoda/Youtube.php:537

need 'return false' or other error for dont die process and repeat via 5-30 seccond, if limit exceeded for controller

ps: sorry for my bad english

**Comment by madcoda** [comment]
you should have a try...catch block wrapping the API calls

```php
try{
    $results = $youtube-> searchVideos("Guilty dogs", 50);
    ....
} catch(Exception $e){
   /* handle error here */
}
```

**Comment by PatSpiegel** [comment]
hm....
just die process
```
try{
 $video = Youtube::getVideoInfo($link);
} catch(Exception $e){
  sleep(60);
  return $this->getVideoInfo($link, $need);
}
```
```
[2015-09-07 17:39:45] production.ERROR: exception 'Exception' with message 'Error 403 Serving Limit Exceeded : servingLimitExceeded' in /var/www/laravel/vendor/madcoda/php-youtube-api/src/Madcoda/Youtube.php:510
Stack trace:
#0 /var/www/laravel/vendor/madcoda/php-youtube-api/src/Madcoda/Youtube.php(124): Madcoda\Youtube->decodeSingle('{\n "error": {\n ...')
#1 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Madcoda\Youtube->getVideoInfo('GUMW7b1ogAc')
#2 /var/www/laravel/workbench/jupeto/melchior/src/Jupeto/Melchior/Youtube.php(141): Illuminate\Support\Facades\Facade::__callStatic('getVideoInfo', Array)
#3 /var/www/laravel/workbench/jupeto/melchior/src/Jupeto/Melchior/Youtube.php(141): Madcoda\Youtube\Facades\Youtube::getVideoInfo('GUMW7b1ogAc')
#4 /var/www/laravel/app/controllers/VideoController.php(281): Jupeto\Melchior\Youtube->getVideoInfo('GUMW7b1ogAc')
#5 [internal function]: VideoController->parserYoutubeKey()
#6 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#7 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('parserYoutubeKe...', Array)
#8 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(VideoController), Object(Illuminate\Routing\Route), 'parserYoutubeKe...')
#9 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'VideoController', 'parserYoutubeKe...')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#12 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/laravel/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/laravel/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
```

**Comment by madcoda** [comment]
Your second call to `->getVideoInfo()` was not wrapped by another try...catch block.
In your case, you want to be able to retry, that is not a correct way to do it.
You should use a for loop / do...while loop.

Here is an example to retry 3 times: (I have not tested the code, adjust as you needed)
```php
$success = false;
$retries = 0;
$video = null;
do{

    try{
        $video = Youtube::getVideoInfo($link);
        $success = true;
        break;
    }catch(Exception $e){
        /* output some errors or logging here */
        sleep(60);
    }
    
}while($success === false && $retries++ < 3);

if($success){
    // do your task here
    echo "Query Youtube API successfully with $retries retries.";
}

```

Good luck!
